server:
  port: 8080
  tomcat:
    resource-cache-ttl: -1

spring:
  application:
    name: store-application
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?reWriteBatchedInserts=true
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      max-poll-records: 100
      properties:
        spring.json.trusted.packages: "com.example.pvpeev.electronics_store.order.dto.*"
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG


storage:
  s3:
    endpoint: "http://localhost:9000"
    region: "dummy" # MinIO doesn't care, but the SDK requires a value
    access-key: ${MINIIO_USER}
    secret-key: ${MINIIO_PASSWORD}
    path-style-access: true # Set to false when moving to AWS S3
